action_repeat: 1
episode_length: 200/${action_repeat}
train_steps: 50000/${action_repeat}
eval_freq: 5000
eval_episodes: 10

# planning
iterations: 6
min_std: 0.0

# learning
max_buffer_size: 200000
seed_steps: 10000
std_schedule: linear(0.5, ${min_std}, 50000)
horizon_schedule: linear(1, ${horizon}, 50000)

# architecture
enc_dim: 128
mlp_dim: 256
latent_dim: 6
